language: english
title: QMIND SSH QKD
theme: just-the-docs
description: Meeting notes and documentation for QKD ssh key generation project

url: https://st4eve.github.io/QMIND-2023-QKD/

color_scheme: dark

format: web

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/st4eve/QMIND-2023-QKD" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

back_to_top: true
back_to_top_text: "Back to top"


nav_external_links:
  - title: QSSH on Github
    url: https://github.com/st4eve/QMIND-2023-QKD


# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "QSSH on Github":
    - "https://github.com/st4eve/QMIND-2023-QKD"

